spring.application.name=watch-store

# Thông tin kết nối MySQL (Đổi username và password cho khớp với XAMPP/MySQL Workbench của bạn)
spring.datasource.url=jdbc:mysql://localhost:3306/watch_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Cấu hình Hibernate (JPA)
# update: Tự động tạo bảng/cột mới dựa trên code Entity mà không làm mất dữ liệu cũ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# In câu lệnh SQL ra console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true